import type { Metadata } from 'next';

import './globals.css';
import { inter } from '@fonts';

export const metadata: Metadata = {
  title: 'Droplo task',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <div className='container'>{children}</div>
      </body>
    </html>
  );
}
