import type { Metadata } from 'next';

import './globals.css';
import { MenuContextProvider } from '@contexts/menu';
import { inter } from '@fonts';
import { WithChildren } from '@types';

export const metadata: Metadata = {
  title: 'Droplo task',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<WithChildren>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <div className='container'>
          <MenuContextProvider>{children}</MenuContextProvider>
        </div>
      </body>
    </html>
  );
}
